services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - lavalink
    environment:
      - DISCORD_TOKEN=
      - LAVALINK_HOST=
      - LAVALINK_PORT=
      - LAVALINK_PASSWORD=
      - LAVALINK_CERTIFICATE=
      - LAVALINK_CERTIFICATE_KEY=

  postgres:
    image: postgres:latest
    networks:
      - lavalink
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=velox
      - POSTGRES_PASSWORD=velox_pwd
      - POSTGRES_DB=velox
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

networks:
  lavalink:
    name: lavalink
